pipeline {
    agent any

    environment {
        JAVA_HOME = "/usr/lib/jvm/java-17-openjdk-amd64"
        ANDROID_HOME = "/var/lib/jenkins/Android/Sdk"
        ANDROID_SDK_ROOT = "/var/lib/jenkins/Android/Sdk"
        FLUTTER_HOME = "/var/lib/jenkins/flutter"
    }

    stages {
        stage('Flutter Doctor') {
            steps {
                sh '/var/lib/jenkins/flutter/bin/flutter doctor'
            }
        }

        stage('Get Dependencies') {
            steps {
                dir('register_system/backend/flutter_app') {
                    sh '/var/lib/jenkins/flutter/bin/flutter pub get'
                }
            }
        }

        stage('Build APK') {
            steps {
                dir('register_system/backend/flutter_app') {
                    sh '/var/lib/jenkins/flutter/bin/flutter build apk --release'
                }
            }
        }
    }
}